nodes:
- input.visual:
    source: true_postive.mp4  #true_negative.mp4   for unsafe condition
- model.yolo
- dabble.bbox_count
- dabble.statistics:
    identity: count
- draw.bbox:
    show_labels: True
- draw.legend:
    show: ["count"]
- custom_nodes.draw.safety
- output.screen
